"""Reference data for lab test validation.

LOINC codes, canonical units, plausibility ranges, default reference ranges.
Plausibility ranges are widened for TRT/HRT patient population — a testosterone
of 5000 ng/dL or hematocrit of 58% is real, not a data error.

Sources: Quest/LabCorp published ranges, LOINC database, Llewellyn's Anabolics.
"""

from __future__ import annotations
from dataclasses import dataclass, field


@dataclass
class TestDefinition:
    loinc_code: str
    canonical_name: str
    canonical_unit: str
    plausibility_min: float
    plausibility_max: float
    default_ref_low_male: float | None = None
    default_ref_high_male: float | None = None
    aliases: list[str] = field(default_factory=list)
    category: str = ""


# --- Test definitions ---
# Each test that commonly appears on TRT/HRT patient bloodwork.
# Aliases cover Quest, LabCorp, Marek, and common shorthand variations.

TEST_DEFINITIONS: list[TestDefinition] = [
    # === HORMONES ===
    TestDefinition(
        loinc_code="2986-8",
        canonical_name="Testosterone, Total",
        canonical_unit="ng/dL",
        plausibility_min=0,
        plausibility_max=15000,  # supraphysiological on exogenous testosterone
        default_ref_low_male=264,
        default_ref_high_male=916,
        aliases=[
            "Testosterone, Total", "Total Testosterone", "TESTOSTERONE,TOTAL",
            "Testosterone Total, MS", "Testosterone, Total, MS",
            "TESTOSTERONE, TOTAL, MS", "Testosterone",
            "Testosterone, Serum", "Testosterone Total LC/MS-MS",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="2258-6",
        canonical_name="Testosterone, Free",
        canonical_unit="pg/mL",
        plausibility_min=0,
        plausibility_max=5000,
        default_ref_low_male=9.3,
        default_ref_high_male=26.5,
        aliases=[
            "Testosterone, Free", "Free Testosterone", "FREE TESTOSTERONE",
            "Testosterone,Free and Total", "Free Testosterone (Direct)",
            "Testosterone Free", "Free T",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="2243-4",
        canonical_name="Estradiol",
        canonical_unit="pg/mL",
        plausibility_min=0,
        plausibility_max=500,
        default_ref_low_male=8.0,
        default_ref_high_male=35.0,
        aliases=[
            "Estradiol", "Estradiol, Sensitive", "ESTRADIOL, SENSITIVE",
            "Estradiol Sensitive LC/MS-MS", "Estradiol,Sensitive,LC/MS/MS",
            "E2", "Estradiol, Sensitive, LC/MS-MS", "ESTRADIOL",
            "Estradiol, Ultra-Sensitive", "Estradiol Ultrasensitive",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="13969-1",
        canonical_name="Estradiol, Standard",
        canonical_unit="pg/mL",
        plausibility_min=0,
        plausibility_max=500,
        default_ref_low_male=8.0,
        default_ref_high_male=35.0,
        aliases=[
            "Estradiol, Standard", "Estradiol (Standard)",
            "Estradiol Immunoassay", "Estradiol, Roche ECLIA",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="10501-5",
        canonical_name="LH",
        canonical_unit="mIU/mL",
        plausibility_min=0,
        plausibility_max=100,
        default_ref_low_male=1.7,
        default_ref_high_male=8.6,
        aliases=[
            "LH", "Luteinizing Hormone", "LUTEINIZING HORMONE (LH)",
            "Luteinizing Hormone(LH), S", "LH, Serum",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="15067-2",
        canonical_name="FSH",
        canonical_unit="mIU/mL",
        plausibility_min=0,
        plausibility_max=100,
        default_ref_low_male=1.5,
        default_ref_high_male=12.4,
        aliases=[
            "FSH", "Follicle Stimulating Hormone",
            "FOLLICLE STIMULATING HORMONE (FSH)", "FSH, Serum",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="2842-3",
        canonical_name="Prolactin",
        canonical_unit="ng/mL",
        plausibility_min=0,
        plausibility_max=500,
        default_ref_low_male=4.0,
        default_ref_high_male=15.2,
        aliases=[
            "Prolactin", "PROLACTIN", "Prolactin, Serum",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="13967-5",
        canonical_name="SHBG",
        canonical_unit="nmol/L",
        plausibility_min=0,
        plausibility_max=300,
        default_ref_low_male=16.5,
        default_ref_high_male=55.9,
        aliases=[
            "SHBG", "Sex Horm Binding Glob, Serum",
            "Sex Hormone Binding Globulin", "SEX HORM BINDING GLOB, SERUM",
            "Sex Hormone-Binding Globulin",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="1668-3",
        canonical_name="DHEA-Sulfate",
        canonical_unit="ug/dL",
        plausibility_min=0,
        plausibility_max=1500,
        default_ref_low_male=138.5,
        default_ref_high_male=475.2,
        aliases=[
            "DHEA-Sulfate", "DHEA-S", "Dehydroepiandrosterone Sulfate",
            "DHEA Sulfate", "DHEA-SO4",
        ],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="1990-1",
        canonical_name="IGF-1",
        canonical_unit="ng/mL",
        plausibility_min=0,
        plausibility_max=1500,
        default_ref_low_male=115,
        default_ref_high_male=355,
        aliases=[
            "IGF-1", "IGF I", "Insulin-Like Growth Factor I",
            "IGF-I", "Somatomedin C", "IGF-1, LC/MS",
        ],
        category="hormones",
    ),

    # === HEMATOLOGY ===
    TestDefinition(
        loinc_code="4544-3",
        canonical_name="Hematocrit",
        canonical_unit="%",
        plausibility_min=15,
        plausibility_max=65,  # enhanced athletes can push high
        default_ref_low_male=37.5,
        default_ref_high_male=51.0,
        aliases=[
            "Hematocrit", "HCT", "Hct", "HEMATOCRIT",
        ],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="718-7",
        canonical_name="Hemoglobin",
        canonical_unit="g/dL",
        plausibility_min=4,
        plausibility_max=22,
        default_ref_low_male=12.6,
        default_ref_high_male=17.7,
        aliases=[
            "Hemoglobin", "Hgb", "HGB", "HEMOGLOBIN",
        ],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="789-8",
        canonical_name="RBC",
        canonical_unit="x10E6/uL",
        plausibility_min=1,
        plausibility_max=10,
        default_ref_low_male=4.14,
        default_ref_high_male=5.80,
        aliases=[
            "RBC", "Red Blood Cell Count", "Red Blood Cells",
            "Erythrocytes", "RBC Count", "Total RBC count",
        ],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="6690-2",
        canonical_name="WBC",
        canonical_unit="x10E3/uL",
        plausibility_min=0.5,
        plausibility_max=50,
        default_ref_low_male=3.4,
        default_ref_high_male=10.8,
        aliases=[
            "WBC", "White Blood Cell Count", "White Blood Cells",
            "Leukocytes", "WBC Count", "Total WBC count",
        ],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="777-3",
        canonical_name="Platelets",
        canonical_unit="x10E3/uL",
        plausibility_min=10,
        plausibility_max=1000,
        default_ref_low_male=150,
        default_ref_high_male=400,
        aliases=[
            "Platelets", "Platelet Count", "PLT", "PLATELETS",
        ],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="787-2",
        canonical_name="MCV",
        canonical_unit="fL",
        plausibility_min=50,
        plausibility_max=130,
        default_ref_low_male=79,
        default_ref_high_male=97,
        aliases=["MCV", "Mean Corpuscular Volume"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="785-6",
        canonical_name="MCH",
        canonical_unit="pg",
        plausibility_min=15,
        plausibility_max=45,
        default_ref_low_male=26.6,
        default_ref_high_male=33.0,
        aliases=["MCH", "Mean Corpuscular Hemoglobin"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="786-4",
        canonical_name="MCHC",
        canonical_unit="g/dL",
        plausibility_min=25,
        plausibility_max=40,
        default_ref_low_male=31.5,
        default_ref_high_male=35.7,
        aliases=["MCHC", "Mean Corpuscular Hemoglobin Concentration"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="788-0",
        canonical_name="RDW",
        canonical_unit="%",
        plausibility_min=8,
        plausibility_max=25,
        default_ref_low_male=11.6,
        default_ref_high_male=15.4,
        aliases=["RDW", "Red Cell Distribution Width", "RDW-CV"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="751-8",
        canonical_name="Neutrophils %",
        canonical_unit="%",
        plausibility_min=0,
        plausibility_max=100,
        default_ref_low_male=40,
        default_ref_high_male=74,
        aliases=["Neutrophils", "Neutrophils %", "Neut %", "Segs"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="751-8-abs",
        canonical_name="Neutrophils Absolute",
        canonical_unit="x10E3/uL",
        plausibility_min=0,
        plausibility_max=30,
        default_ref_low_male=1.4,
        default_ref_high_male=7.0,
        aliases=["Neutrophils (Absolute)", "Abs Neutrophils", "Neutrophils Abs",
                 "Neutrophils, Absolute"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="736-9",
        canonical_name="Lymphocytes %",
        canonical_unit="%",
        plausibility_min=0,
        plausibility_max=100,
        default_ref_low_male=14,
        default_ref_high_male=46,
        aliases=["Lymphs", "Lymphocytes", "Lymphocytes %", "Lymph %"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="736-9-abs",
        canonical_name="Lymphocytes Absolute",
        canonical_unit="x10E3/uL",
        plausibility_min=0,
        plausibility_max=20,
        default_ref_low_male=0.7,
        default_ref_high_male=3.1,
        aliases=["Lymphs (Absolute)", "Abs Lymphocytes", "Lymphocytes Abs",
                 "Lymphocytes, Absolute"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="5905-5",
        canonical_name="Monocytes %",
        canonical_unit="%",
        plausibility_min=0,
        plausibility_max=30,
        default_ref_low_male=4,
        default_ref_high_male=13,
        aliases=["Monocytes", "Monocytes %", "Mono %"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="5905-5-abs",
        canonical_name="Monocytes Absolute",
        canonical_unit="x10E3/uL",
        plausibility_min=0,
        plausibility_max=5,
        default_ref_low_male=0.1,
        default_ref_high_male=0.9,
        aliases=["Monocytes(Absolute)", "Monocytes (Absolute)", "Abs Monocytes",
                 "Monocytes Abs"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="713-8",
        canonical_name="Eosinophils %",
        canonical_unit="%",
        plausibility_min=0,
        plausibility_max=30,
        default_ref_low_male=0,
        default_ref_high_male=7,
        aliases=["Eos", "Eosinophils", "Eosinophils %", "Eos %"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="713-8-abs",
        canonical_name="Eosinophils Absolute",
        canonical_unit="x10E3/uL",
        plausibility_min=0,
        plausibility_max=5,
        default_ref_low_male=0.0,
        default_ref_high_male=0.4,
        aliases=["Eos (Absolute)", "Eosinophils (Absolute)", "Abs Eosinophils"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="706-2",
        canonical_name="Basophils %",
        canonical_unit="%",
        plausibility_min=0,
        plausibility_max=10,
        default_ref_low_male=0,
        default_ref_high_male=3,
        aliases=["Basos", "Basophils", "Basophils %", "Baso %"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="706-2-abs",
        canonical_name="Basophils Absolute",
        canonical_unit="x10E3/uL",
        plausibility_min=0,
        plausibility_max=3,
        default_ref_low_male=0.0,
        default_ref_high_male=0.2,
        aliases=["Baso (Absolute)", "Basophils (Absolute)", "Abs Basophils"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="38518-7",
        canonical_name="Immature Granulocytes %",
        canonical_unit="%",
        plausibility_min=0,
        plausibility_max=10,
        default_ref_low_male=0,
        default_ref_high_male=1,
        aliases=["Immature Granulocytes", "Immature Granulocytes %", "IG %"],
        category="hematology",
    ),
    TestDefinition(
        loinc_code="38518-7-abs",
        canonical_name="Immature Granulocytes Absolute",
        canonical_unit="x10E3/uL",
        plausibility_min=0,
        plausibility_max=3,
        default_ref_low_male=0.0,
        default_ref_high_male=0.1,
        aliases=["Immature Grans (Abs)", "Immature Granulocytes (Absolute)", "IG Abs"],
        category="hematology",
    ),

    # === LIPIDS ===
    TestDefinition(
        loinc_code="2093-3",
        canonical_name="Cholesterol, Total",
        canonical_unit="mg/dL",
        plausibility_min=50,
        plausibility_max=500,
        default_ref_low_male=100,
        default_ref_high_male=199,
        aliases=[
            "Cholesterol, Total", "Total Cholesterol", "CHOLESTEROL, TOTAL",
            "Cholesterol", "TC",
        ],
        category="lipids",
    ),
    TestDefinition(
        loinc_code="2085-9",
        canonical_name="HDL Cholesterol",
        canonical_unit="mg/dL",
        plausibility_min=5,
        plausibility_max=150,
        default_ref_low_male=40,
        default_ref_high_male=None,  # no upper bound concern
        aliases=[
            "HDL Cholesterol", "HDL", "HDL-C",
            "HDL CHOLESTEROL", "Cholesterol, HDL",
        ],
        category="lipids",
    ),
    TestDefinition(
        loinc_code="2089-1",
        canonical_name="LDL Cholesterol",
        canonical_unit="mg/dL",
        plausibility_min=10,
        plausibility_max=500,
        default_ref_low_male=0,
        default_ref_high_male=99,
        aliases=[
            "LDL Cholesterol", "LDL", "LDL-C", "LDL Chol Calc",
            "LDL CHOLESTEROL CALC", "LDL Cholesterol Calc",
            "Cholesterol, LDL, Calculated",
        ],
        category="lipids",
    ),
    TestDefinition(
        loinc_code="2571-8",
        canonical_name="Triglycerides",
        canonical_unit="mg/dL",
        plausibility_min=10,
        plausibility_max=2000,
        default_ref_low_male=0,
        default_ref_high_male=149,
        aliases=[
            "Triglycerides", "TRIGLYCERIDES", "Trigs", "TG",
        ],
        category="lipids",
    ),
    TestDefinition(
        loinc_code="43396-1",
        canonical_name="VLDL Cholesterol",
        canonical_unit="mg/dL",
        plausibility_min=0,
        plausibility_max=200,
        default_ref_low_male=5,
        default_ref_high_male=40,
        aliases=["VLDL Cholesterol Cal", "VLDL", "VLDL-C"],
        category="lipids",
    ),

    # === LIVER ===
    TestDefinition(
        loinc_code="1742-6",
        canonical_name="ALT",
        canonical_unit="U/L",
        plausibility_min=0,
        plausibility_max=2000,  # orals can spike hard
        default_ref_low_male=0,
        default_ref_high_male=44,
        aliases=[
            "ALT", "SGPT", "Alanine Aminotransferase",
            "ALT (SGPT)", "Alanine Aminotransferase (ALT/SGPT)",
        ],
        category="liver",
    ),
    TestDefinition(
        loinc_code="1920-8",
        canonical_name="AST",
        canonical_unit="U/L",
        plausibility_min=0,
        plausibility_max=2000,
        default_ref_low_male=0,
        default_ref_high_male=40,
        aliases=[
            "AST", "SGOT", "Aspartate Aminotransferase",
            "AST (SGOT)", "Aspartate Aminotransferase (AST/SGOT)",
        ],
        category="liver",
    ),
    TestDefinition(
        loinc_code="6768-6",
        canonical_name="Alkaline Phosphatase",
        canonical_unit="U/L",
        plausibility_min=0,
        plausibility_max=1000,
        default_ref_low_male=44,
        default_ref_high_male=121,
        aliases=[
            "Alkaline Phosphatase", "Alk Phos", "ALP",
            "ALKALINE PHOSPHATASE", "Alkaline Phosphatase, S",
        ],
        category="liver",
    ),
    TestDefinition(
        loinc_code="1975-2",
        canonical_name="Bilirubin, Total",
        canonical_unit="mg/dL",
        plausibility_min=0,
        plausibility_max=30,
        default_ref_low_male=0.0,
        default_ref_high_male=1.2,
        aliases=[
            "Bilirubin, Total", "Total Bilirubin", "BILIRUBIN, TOTAL",
            "Bilirubin",
            "Bilirubin Total", "T. Bilirubin",
        ],
        category="liver",
    ),
    TestDefinition(
        loinc_code="1968-7",
        canonical_name="Bilirubin, Direct",
        canonical_unit="mg/dL",
        plausibility_min=0,
        plausibility_max=20,
        default_ref_low_male=0.0,
        default_ref_high_male=0.4,
        aliases=[
            "Bilirubin, Direct", "Direct Bilirubin", "BILIRUBIN, DIRECT",
        ],
        category="liver",
    ),
    TestDefinition(
        loinc_code="2324-2",
        canonical_name="GGT",
        canonical_unit="U/L",
        plausibility_min=0,
        plausibility_max=1000,
        default_ref_low_male=0,
        default_ref_high_male=65,
        aliases=[
            "GGT", "Gamma Glutamyl Transferase",
            "Gamma-Glutamyl Transpeptidase", "GGTP",
        ],
        category="liver",
    ),
    TestDefinition(
        loinc_code="2885-2",
        canonical_name="Protein, Total",
        canonical_unit="g/dL",
        plausibility_min=2,
        plausibility_max=14,
        default_ref_low_male=6.0,
        default_ref_high_male=8.5,
        aliases=["Protein, Total, Serum", "Total Protein", "Protein, Total"],
        category="liver",
    ),
    TestDefinition(
        loinc_code="1751-7",
        canonical_name="Albumin",
        canonical_unit="g/dL",
        plausibility_min=1,
        plausibility_max=7,
        default_ref_low_male=3.5,
        default_ref_high_male=5.5,
        aliases=["Albumin", "Albumin, Serum", "ALBUMIN, SERUM"],
        category="liver",
    ),
    TestDefinition(
        loinc_code="10834-0",
        canonical_name="Globulin, Total",
        canonical_unit="g/dL",
        plausibility_min=0.5,
        plausibility_max=7,
        default_ref_low_male=1.5,
        default_ref_high_male=4.5,
        aliases=["Globulin, Total", "Globulin", "Total Globulin"],
        category="liver",
    ),
    TestDefinition(
        loinc_code="1759-0",
        canonical_name="A/G Ratio",
        canonical_unit="ratio",
        plausibility_min=0.1,
        plausibility_max=5,
        default_ref_low_male=1.2,
        default_ref_high_male=2.2,
        aliases=["A/G Ratio", "Albumin/Globulin Ratio"],
        category="liver",
    ),

    # === KIDNEY ===
    TestDefinition(
        loinc_code="38483-4",
        canonical_name="Creatinine",
        canonical_unit="mg/dL",
        plausibility_min=0.1,
        plausibility_max=20,
        default_ref_low_male=0.76,
        default_ref_high_male=1.27,
        aliases=[
            "Creatinine", "Creatinine, Serum", "CREATININE, SERUM",
            "Creatinine Serum",
        ],
        category="kidney",
    ),
    TestDefinition(
        loinc_code="3094-0",
        canonical_name="BUN",
        canonical_unit="mg/dL",
        plausibility_min=1,
        plausibility_max=150,
        default_ref_low_male=6,
        default_ref_high_male=20,
        aliases=[
            "BUN", "Urea Nitrogen", "Blood Urea Nitrogen",
            "BUN, Serum",
        ],
        category="kidney",
    ),
    TestDefinition(
        loinc_code="3097-3",
        canonical_name="BUN/Creatinine Ratio",
        canonical_unit="ratio",
        plausibility_min=1,
        plausibility_max=50,
        default_ref_low_male=8,
        default_ref_high_male=27,
        aliases=["BUN/Creatinine Ratio", "BUN/Creat Ratio"],
        category="kidney",
    ),
    TestDefinition(
        loinc_code="33914-3",
        canonical_name="eGFR",
        canonical_unit="mL/min/1.73",
        plausibility_min=5,
        plausibility_max=200,
        default_ref_low_male=60,
        default_ref_high_male=None,
        aliases=[
            "eGFR", "GFR", "Glomerular Filtration Rate",
            "eGFR If NonAfricn Am", "eGFR If Africn Am",
            "eGFR Non-Afr. American", "eGFR Afr. American",
            "eGFR Non-African American", "eGFR African American",
            "Estimated GFR", "Est. GFR", "GFR, Estimated",
            "eGFR (CKD-EPI)", "eGFR CKD-EPI",
            "Glom Filt Rate, Est", "GFR Estimated",
            "eGFR (Non-Afr-Am)", "eGFR (Afr-Am)",
            "eGFR Non-Afr Am", "eGFR Afr Am",
            "eGFR If Non-Afr. Am", "eGFR If Afr. Am",
        ],
        category="kidney",
    ),
    TestDefinition(
        loinc_code="76485-2",
        canonical_name="Cystatin C",
        canonical_unit="mg/L",
        plausibility_min=0.1,
        plausibility_max=10,
        default_ref_low_male=0.62,
        default_ref_high_male=0.92,
        aliases=["Cystatin C", "Cystatin-C"],
        category="kidney",
    ),

    # === ELECTROLYTES / METABOLIC ===
    TestDefinition(
        loinc_code="2345-7",
        canonical_name="Glucose",
        canonical_unit="mg/dL",
        plausibility_min=20,
        plausibility_max=600,
        default_ref_low_male=65,
        default_ref_high_male=99,
        aliases=[
            "Glucose", "Glucose, Serum", "GLUCOSE, SERUM", "Fasting Glucose",
        ],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2951-2",
        canonical_name="Sodium",
        canonical_unit="mmol/L",
        plausibility_min=110,
        plausibility_max=170,
        default_ref_low_male=134,
        default_ref_high_male=144,
        aliases=["Sodium", "Sodium, Serum", "Na"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2823-3",
        canonical_name="Potassium",
        canonical_unit="mmol/L",
        plausibility_min=2,
        plausibility_max=8,
        default_ref_low_male=3.5,
        default_ref_high_male=5.2,
        aliases=["Potassium", "Potassium, Serum", "K"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2075-0",
        canonical_name="Chloride",
        canonical_unit="mmol/L",
        plausibility_min=80,
        plausibility_max=120,
        default_ref_low_male=96,
        default_ref_high_male=106,
        aliases=["Chloride", "Chloride, Serum", "Cl"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="1963-8",
        canonical_name="Bicarbonate",
        canonical_unit="mmol/L",
        plausibility_min=10,
        plausibility_max=40,
        default_ref_low_male=18,
        default_ref_high_male=29,
        aliases=["CO2", "Carbon Dioxide, Total", "Bicarbonate", "CO2, Total",
                 "CARBON DIOXIDE", "Carbon Dioxide", "CO2, Total"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="17861-6",
        canonical_name="Calcium",
        canonical_unit="mg/dL",
        plausibility_min=5,
        plausibility_max=16,
        default_ref_low_male=8.7,
        default_ref_high_male=10.2,
        aliases=["Calcium", "Calcium, Serum", "Ca"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2777-1",
        canonical_name="Phosphorus",
        canonical_unit="mg/dL",
        plausibility_min=1,
        plausibility_max=10,
        default_ref_low_male=2.5,
        default_ref_high_male=4.5,
        aliases=["Phosphorus", "Phosphate", "Phosphorus, Serum"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="19123-9",
        canonical_name="Magnesium",
        canonical_unit="mg/dL",
        plausibility_min=0.5,
        plausibility_max=5,
        default_ref_low_male=1.6,
        default_ref_high_male=2.6,
        aliases=["Magnesium", "Magnesium, Serum", "Mg"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2532-0",
        canonical_name="Iron",
        canonical_unit="ug/dL",
        plausibility_min=10,
        plausibility_max=500,
        default_ref_low_male=38,
        default_ref_high_male=169,
        aliases=["Iron", "Iron, Serum", "IRON, SERUM", "Iron Bind.Cap.(TIBC)", "Iron, Total"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2502-3",
        canonical_name="Iron Saturation",
        canonical_unit="%",
        plausibility_min=1,
        plausibility_max=100,
        default_ref_low_male=15,
        default_ref_high_male=55,
        aliases=["Iron Saturation", "TIBC Saturation", "Iron % Saturation", "% Saturation"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2276-4",
        canonical_name="Ferritin",
        canonical_unit="ng/mL",
        plausibility_min=1,
        plausibility_max=2000,
        default_ref_low_male=30,
        default_ref_high_male=400,
        aliases=["Ferritin", "Ferritin, Serum", "FERRITIN, SERUM"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="4548-4",
        canonical_name="Hemoglobin A1c",
        canonical_unit="%",
        plausibility_min=3,
        plausibility_max=18,
        default_ref_low_male=4.8,
        default_ref_high_male=5.6,
        aliases=[
            "Hemoglobin A1c", "HbA1c", "A1C", "Glycated Hemoglobin",
            "Hemoglobin A1C", "HGB A1C",
        ],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="14749-6",
        canonical_name="Fasting Insulin",
        canonical_unit="uIU/mL",
        plausibility_min=0,
        plausibility_max=300,
        default_ref_low_male=2.6,
        default_ref_high_male=24.9,
        aliases=["Insulin", "Fasting Insulin", "Insulin, Fasting"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="14933-6",
        canonical_name="Uric Acid",
        canonical_unit="mg/dL",
        plausibility_min=0.5,
        plausibility_max=20,
        default_ref_low_male=3.7,
        default_ref_high_male=8.6,
        aliases=["Uric Acid", "Uric Acid, Serum", "URIC ACID, SERUM"],
        category="metabolic",
    ),

    # === THYROID ===
    TestDefinition(
        loinc_code="3016-3",
        canonical_name="TSH",
        canonical_unit="uIU/mL",
        plausibility_min=0.01,
        plausibility_max=100,
        default_ref_low_male=0.45,
        default_ref_high_male=4.5,
        aliases=[
            "TSH", "Thyroid Stimulating Hormone", "TSH, Serum",
            "THYROID STIMULATING HORMONE (TSH)",
        ],
        category="thyroid",
    ),
    TestDefinition(
        loinc_code="3026-2",
        canonical_name="Free T4",
        canonical_unit="ng/dL",
        plausibility_min=0.1,
        plausibility_max=10,
        default_ref_low_male=0.82,
        default_ref_high_male=1.77,
        aliases=[
            "Free T4", "T4, Free", "Free Thyroxine", "FT4",
            "T4,Free(Direct)", "Thyroxine (T4) Free, Direct, S",
        ],
        category="thyroid",
    ),
    TestDefinition(
        loinc_code="3053-6",
        canonical_name="Free T3",
        canonical_unit="pg/mL",
        plausibility_min=0.5,
        plausibility_max=10,
        default_ref_low_male=2.0,
        default_ref_high_male=4.4,
        aliases=[
            "Free T3", "T3, Free", "Triiodothyronine (T3), Free, Serum",
            "FT3", "Triiodothyronine, Free",
        ],
        category="thyroid",
    ),

    # === CARDIAC / INFLAMMATION ===
    TestDefinition(
        loinc_code="30522-7",
        canonical_name="hs-CRP",
        canonical_unit="mg/L",
        plausibility_min=0,
        plausibility_max=300,
        default_ref_low_male=0,
        default_ref_high_male=3.0,
        aliases=[
            "hs-CRP", "C-Reactive Protein, Cardiac",
            "CRP, High Sensitivity", "hsCRP",
            "C-Reactive Protein, High Sensitivity",
        ],
        category="cardiac",
    ),
    TestDefinition(
        loinc_code="30392-5",
        canonical_name="Homocysteine",
        canonical_unit="umol/L",
        plausibility_min=1,
        plausibility_max=100,
        default_ref_low_male=0,
        default_ref_high_male=10.4,
        aliases=["Homocysteine", "Homocysteine, Plasma", "HOMOCYSTEINE"],
        category="cardiac",
    ),
    TestDefinition(
        loinc_code="43394-6",
        canonical_name="Lp(a)",
        canonical_unit="nmol/L",
        plausibility_min=0,
        plausibility_max=500,
        default_ref_low_male=0,
        default_ref_high_male=75,
        aliases=[
            "Lp(a)", "Lipoprotein(a)", "Lipoprotein (a)",
            "Lp(a)-P", "LIPOPROTEIN (a)",
        ],
        category="cardiac",
    ),
    TestDefinition(
        loinc_code="49132-4",
        canonical_name="ApoB",
        canonical_unit="mg/dL",
        plausibility_min=10,
        plausibility_max=300,
        default_ref_low_male=0,
        default_ref_high_male=100,
        aliases=[
            "ApoB", "Apolipoprotein B", "Apolipoprotein B, Serum",
        ],
        category="cardiac",
    ),

    # === VITAMINS ===
    TestDefinition(
        loinc_code="1989-3",
        canonical_name="Vitamin D, 25-Hydroxy",
        canonical_unit="ng/mL",
        plausibility_min=3,
        plausibility_max=200,
        default_ref_low_male=30,
        default_ref_high_male=100,
        aliases=[
            "Vitamin D, 25-Hydroxy", "25-Hydroxyvitamin D",
            "Vitamin D, 25-OH", "Vit D, 25-OH, Total",
            "25-OH Vitamin D", "Vitamin D",
        ],
        category="vitamins",
    ),
    TestDefinition(
        loinc_code="2132-9",
        canonical_name="Vitamin B12",
        canonical_unit="pg/mL",
        plausibility_min=50,
        plausibility_max=3000,
        default_ref_low_male=232,
        default_ref_high_male=1245,
        aliases=["Vitamin B12", "B12", "Cobalamin"],
        category="vitamins",
    ),
    TestDefinition(
        loinc_code="2284-8",
        canonical_name="Folate",
        canonical_unit="ng/mL",
        plausibility_min=1,
        plausibility_max=50,
        default_ref_low_male=2.5,
        default_ref_high_male=None,
        aliases=["Folate", "Folate (Folic Acid), Serum", "Folic Acid"],
        category="vitamins",
    ),

    # === PSA ===
    TestDefinition(
        loinc_code="2857-1",
        canonical_name="PSA",
        canonical_unit="ng/mL",
        plausibility_min=0,
        plausibility_max=100,
        default_ref_low_male=0,
        default_ref_high_male=4.0,
        aliases=[
            "PSA", "Prostate Specific Antigen",
            "PSA, Total", "Prostate-Specific Ag, Serum",
        ],
        category="prostate",
    ),

    # === COMMONLY MISSED TESTS (added to reduce unmapped results) ===
    TestDefinition(
        loinc_code="2500-7",
        canonical_name="TIBC",
        canonical_unit="ug/dL",
        plausibility_min=100, plausibility_max=600,
        default_ref_low_male=250, default_ref_high_male=370,
        aliases=["TIBC", "Iron Bind.Cap.(TIBC)", "Total Iron Binding Capacity", "Iron Binding Capacity"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2143-6",
        canonical_name="Cortisol",
        canonical_unit="ug/dL",
        plausibility_min=0, plausibility_max=50,
        default_ref_low_male=6.2, default_ref_high_male=19.4,
        aliases=["Cortisol", "Cortisol, Total", "Cortisol AM", "Cortisol, Serum", "CORTISOL"],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="1554-5",
        canonical_name="DHT",
        canonical_unit="ng/dL",
        plausibility_min=0, plausibility_max=500,
        default_ref_low_male=30, default_ref_high_male=85,
        aliases=["DHT", "Dihydrotestosterone", "5-Alpha DHT"],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="2839-9",
        canonical_name="Pregnenolone",
        canonical_unit="ng/dL",
        plausibility_min=0, plausibility_max=500,
        default_ref_low_male=33, default_ref_high_male=248,
        aliases=["Pregnenolone", "Pregnenolone, MS"],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="2839-2",
        canonical_name="Progesterone",
        canonical_unit="ng/mL",
        plausibility_min=0, plausibility_max=20,
        default_ref_low_male=0.0, default_ref_high_male=0.5,
        aliases=["Progesterone", "Progesterone, Serum"],
        category="hormones",
    ),
    TestDefinition(
        loinc_code="2157-6",
        canonical_name="CK",
        canonical_unit="U/L",
        plausibility_min=20, plausibility_max=50000,
        default_ref_low_male=44, default_ref_high_male=196,
        aliases=["CK", "Creatine Kinase", "CPK", "Creatine Kinase, Total", "CK, Total"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="2532-0-tibc",
        canonical_name="UIBC",
        canonical_unit="ug/dL",
        plausibility_min=50, plausibility_max=400,
        default_ref_low_male=131, default_ref_high_male=425,
        aliases=["UIBC", "Unsaturated Iron Binding Capacity", "Unsaturated Iron-Binding Cap."],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="4537-7",
        canonical_name="Sed Rate",
        canonical_unit="mm/hr",
        plausibility_min=0, plausibility_max=100,
        default_ref_low_male=0, default_ref_high_male=15,
        aliases=["Sed Rate", "ESR", "Sedimentation Rate", "Sedimentation Rate-Westergren", "Sed Rate-Westergren"],
        category="cardiac",
    ),
    TestDefinition(
        loinc_code="2040-3",
        canonical_name="LDH",
        canonical_unit="U/L",
        plausibility_min=50, plausibility_max=1000,
        default_ref_low_male=120, default_ref_high_male=246,
        aliases=["LDH", "Lactate Dehydrogenase", "LD"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="30313-1",
        canonical_name="Hemoglobin A1c (IFCC)",
        canonical_unit="mmol/mol",
        plausibility_min=15, plausibility_max=150,
        default_ref_low_male=20, default_ref_high_male=42,
        aliases=["HbA1c (IFCC)", "A1C IFCC", "Hemoglobin A1c IFCC"],
        category="metabolic",
    ),
    TestDefinition(
        loinc_code="1742-6-v2",
        canonical_name="ALT (SGPT)",
        canonical_unit="U/L",
        plausibility_min=0, plausibility_max=2000,
        default_ref_low_male=0, default_ref_high_male=44,
        aliases=["SGPT", "Alanine Aminotransferase (ALT/SGPT)", "ALT/SGPT", "ALT(SGPT)"],
        category="liver",
    ),
    TestDefinition(
        loinc_code="1920-8-v2",
        canonical_name="AST (SGOT)",
        canonical_unit="U/L",
        plausibility_min=0, plausibility_max=2000,
        default_ref_low_male=0, default_ref_high_male=40,
        aliases=["SGOT", "Aspartate Aminotransferase (AST/SGOT)", "AST/SGOT", "AST(SGOT)"],
        category="liver",
    ),
    TestDefinition(
        loinc_code="49765-1",
        canonical_name="Anion Gap",
        canonical_unit="mmol/L",
        plausibility_min=0, plausibility_max=30,
        default_ref_low_male=7, default_ref_high_male=15,
        aliases=["Anion Gap", "AG"],
        category="metabolic",
    ),
]


def _build_alias_index() -> dict[str, TestDefinition]:
    """Build a case-insensitive alias → TestDefinition lookup."""
    index: dict[str, TestDefinition] = {}
    for td in TEST_DEFINITIONS:
        index[td.canonical_name.lower()] = td
        for alias in td.aliases:
            index[alias.lower()] = td
    return index


ALIAS_INDEX: dict[str, TestDefinition] = _build_alias_index()
